import {
  LayoutDashboard, FileText, Building2, Users, Calendar, Folder, BarChart3, Settings,
  PlusSquare, Upload, Zap, CheckCircle2, Clock, Eye, Download, Flag, Bell, Search,
  Send, Sparkles, ShieldCheck, FileCheck, History, AlertTriangle, CheckCircle,
  ArrowRight, FileClock, FileStack, Gavel, Database, Copy, ClipboardCheck
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  DocumentGen: FileText,
  Associations: Building2,
  UnitOwners: Users,
  Schedule: Calendar,
  Documents: Folder,
  Memory: Database,
  Reports: BarChart3,
  Settings: Settings,
  Plus: PlusSquare,
  Upload: Upload,
  Run: Zap,
  Check: CheckCircle2,
  Time: Clock,
  View: Eye,
  Download: Download,
  Flag: Flag,
  Notification: Bell,
  Search: Search,
  Send: Send,
  AI: Sparkles,
  History: ShieldCheck,
  ShieldCheck: ShieldCheck,
  FileCheck: FileCheck,
  Alert: AlertTriangle,
  Success: CheckCircle,
  Next: ArrowRight,
  FileClock: FileClock,
  FileStack: FileStack,
  Legal: Gavel,
  Copy: Copy,
  Copied: ClipboardCheck,
  Associations: Building2,
};
